version: '3.8'
services:
  frontend:
    image: 992382689365.dkr.ecr.us-east-1.amazonaws.com/despacho-frontend:latest
    container_name: frontend
    ports:
      - "80:3000"   
      - "3001:3001"  
    volumes:
      - ./db.json:/app/db.json
    restart: unless-stopped