version: '3.8'

services:

  frontend:
    build: ./front_despacho
    image: dockermasterluka/despacho-frontend:${VERSION:-v1}
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - nginx-logs:/var/log/nginx
    restart: unless-stopped

  despacho-backend:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    image: dockermasterluka/despachos-backend:${VERSION:-v1}
    container_name: despacho-backend
    ports:
      - "8081:8081"
    environment:
      DB_ENDPOINT: db-despacho
      DB_PORT: 3306
      DB_NAME: despacho_db
      DB_USERNAME: root
      DB_PASSWORD: innovatech2025
    depends_on:
      - db-despacho
    restart: unless-stopped

  ventas-backend:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    image: dockermasterluka/ventas-backend:${VERSION:-v1}
    container_name: ventas-backend
    ports:
      - "8080:8080"
    environment:
      DB_ENDPOINT: db-ventas
      DB_PORT: 3306
      DB_NAME: ventas_db
      DB_USERNAME: root
      DB_PASSWORD: innovatech2025
    depends_on:
      - db-ventas
    restart: unless-stopped

  db-despacho:
    image: mysql:8
    container_name: mysql-despacho
    environment:
      MYSQL_ROOT_PASSWORD: innovatech2025
      MYSQL_DATABASE: despacho_db
    volumes:
      - despacho-db-data:/var/lib/mysql
    restart: unless-stopped

  db-ventas:
    image: mysql:8
    container_name: mysql-ventas
    environment:
      MYSQL_ROOT_PASSWORD: innovatech2025
      MYSQL_DATABASE: ventas_db
    volumes:
      - ventas-db-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  nginx-logs:
    driver: local
  despacho-db-data:
    driver: local
  ventas-db-data:
    driver: local