version: '3.8'
services:
  frontend:
    image: dockermasterluka/despacho-frontend:${VERSION:-v1}
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - nginx-logs:/var/log/nginx
    restart: unless-stopped

volumes:
  nginx-logs:
    driver: local